## Project
name: vending_machine_dbt
version: "1.0"
config-version: 2
profile: vending_machine_dbt

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  vending_machine_dbt:
    staging:
      +materialized: view
    mart:
      +materialized: table
