vending_machine_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: de_role
      database: INSTRUCTOR2_DB_vending_machine_dbt_db
      schema: dev
      warehouse: INSTRUCTOR2_DB_VENDING_MACHINE_DBT_WH
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: de_role
      database: INSTRUCTOR2_DB_vending_machine_dbt_db
      schema: prod
      warehouse: INSTRUCTOR2_DB_vending_machine_dbt_wh
